#!/usr/bin/env python3
""" (M6 ontology-bridge S1) — target-node metadata registry generator.

Runs the repository's pinned `llvm-tblgen --dump-json` over a standalone target-node
`.td` (the single source of truth for the typed target-model statement kinds, )
and emits a DETERMINISTIC, committed X-macro registry `.inc`. The `.inc` is expanded
by the backend model header into (a) the `Kind` enum and (b) a node-metadata table
consumed by the completeness self-test + `check_target_node_registry.py`.

This generator is the "custom consumer" the  pilot proves (the  boundary
permits a small custom tblgen backend OR consumer). It LABELS already-legalized node
shapes; it reads no capability-spec/semantic data.

Determinism: records are sorted by (Model, Ordinal, name) and every field is
emitted in a fixed column order, so regenerating twice from the same `.td`
yields byte-identical output (the deterministic-order gate).

The backend identity (C++ namespace `<Target>_model`, model types, and committed
X-macro names) is REGISTRY-DERIVED from the record fields — no
`--target`/`--macro` arg — so any backend joins by adding its `.td`.

Usage:
    gen_target_node_registry.py --td FILE.td --out FILE.inc
                                [--printer-out FILE.inc]
                                [--tblgen /path/to/llvm-tblgen] [--check]

--check regenerates in-memory and compares to the committed --out (exit 1 if stale),
without rewriting it — the stale-generated-output gate.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))


PINNED_MAJOR = "15"  # the repository's pinned LLVM/MLIR toolchain ()
# `lines` renders a FLAT multi-line statement (): its Syntax is a
# newline-joined template projected once, then split on `\n` into N sibling lines
# at the current indent. Like `line`/`blank` it is terminal (leaf); `block` and
# `flat-block` nest children — `block` indents them one level, `flat-block`
# () keeps them at the frame's own indent (the flat  guard).
SUPPORTED_LAYOUTS = {"line", "commented-line", "blank", "block", "flat-block",
                     "lines", "framed-lines"}
# The nesting (non-leaf, child-framing) layouts: they carry an open pattern +
# CloseSyntax close + typed children. Every other layout is terminal (leaf).
NESTING_LAYOUTS = {"block", "flat-block"}


def _is_pinned(cand):
    # The producer REWRITES the committed artifact, so it must resolve the pinned
    # LLVM major or refuse — a later CI stale check is not equivalent to pinned
    # generation. Verify `<tblgen> --version` reports the pinned major.
    if not (cand and os.path.isfile(cand) and os.access(cand, os.X_OK)):
        return False
    try:
        v = subprocess.run([cand, "--version"], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return False
    return v.returncode == 0 and re.search(rf"LLVM version {re.escape(PINNED_MAJOR)}\.", v.stdout) is not None


def find_tblgen(explicit):
    # Pinned LLVM/MLIR TableGen toolchain (): prefer the explicit path (CMake
    # passes ${LLVM_TOOLS_BINARY_DIR}/llvm-tblgen), then $LLVM_TABLEGEN, then the
    # CMakeCache-pinned llvm@15 keg, then PATH — and REFUSE any candidate whose
    # `--version` is not the pinned LLVM major, so the committed artifact can only
    # be regenerated by the pinned tool (fail closed).
    cands = [explicit, os.environ.get("LLVM_TABLEGEN"), os.environ.get("MLIR_TABLEGEN_EXE")]
    cache = os.path.join(REPO, "out", "CMakeCache.txt")
    if os.path.isfile(cache):
        for line in open(cache, encoding="utf-8"):
            if line.startswith("LLVM_DIR:") or line.startswith("MLIR_DIR:"):
                # …/llvm@15/lib/cmake/{llvm,mlir} -> …/llvm@15/bin/llvm-tblgen
                root = line.split("=", 1)[1].strip()
                for _ in range(3):
                    root = os.path.dirname(root)
                cands.append(os.path.join(root, "bin", "llvm-tblgen"))
    cands.append(shutil.which("llvm-tblgen"))
    for cand in cands:
        if _is_pinned(cand):
            return cand
    seen = [c for c in cands if c]
    sys.exit(f"gen_target_node_registry: no PINNED llvm-tblgen (LLVM {PINNED_MAJOR}.x) found among "
             f"{seen or '[]'} — pass --tblgen pointing at the repository's pinned LLVM {PINNED_MAJOR} tool")


def records(td, tblgen):
    # The tblgen include root is `lib/backends` — the `.td` includes the shared
    # schema as `include "TargetPrinter.td"` and backend-local files as
    # `include "<backend>/…"`. A flat backend `.td` lives at `backends/<backend>/
    # Foo.td` (grandparent == backends);  R1 nests Solidity's `.td` one level
    # deeper under `model/`, so resolve the include root by walking up to the
    # `backends` directory instead of assuming a fixed depth. Behavior is
    # identical for the flat layout (grandparent already IS `backends`).
    include_dir = os.path.dirname(os.path.dirname(td))
    probe = os.path.dirname(td)
    while os.path.basename(probe) and os.path.dirname(probe) != probe:
        if os.path.basename(probe) == "backends":
            include_dir = probe
            break
        probe = os.path.dirname(probe)
    out = subprocess.run([tblgen, "-I", include_dir, "--dump-json", td],
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"gen_target_node_registry: llvm-tblgen failed on {td}:\n{out.stderr}")
    data = json.loads(out.stdout)
    # Backend-agnostic discovery: every node record derives from the shared
    # TargetPrinterNode base class, so any backend's `.td` is picked up without a
    # per-backend class name baked into the generator.
    names = data.get("!instanceof", {}).get("TargetPrinterNode", [])
    recs = []
    for name in names:
        r = data[name]
        fields = []
        for f in r.get("Fields", []):
            fname = f["def"] if isinstance(f, dict) else f
            fields.append({
                "name": str(data[fname]["Name"]),
                "index": int(data[fname]["Index"]),
                "prefix": str(data[fname].get("Prefix", "")),
            })
        enum_fields = []
        for ef in r.get("EnumFields", []):
            efname = ef["def"] if isinstance(ef, dict) else ef
            efd = data[efname]
            sp = efd["Spelling"]
            spname = sp["def"] if isinstance(sp, dict) else sp
            enum_fields.append({
                "name": str(efd["Name"]),
                "spellingSym": str(spname),
                "cppType": str(data[spname]["CppType"]),
                "symbols": [str(s) for s in data[spname]["Symbols"]],
                "spellings": [str(s) for s in data[spname]["Spellings"]],
                "repeated": bool(int(efd["Repeated"])),
                "inner": str(efd.get("Inner", "")),
                "prefix": str(efd.get("Prefix", "")),
            })
        item_fields = []
        for f in r.get("ItemFields", []):
            fname = f["def"] if isinstance(f, dict) else f
            item_fields.append({
                "name": str(data[fname]["Name"]),
                "index": int(data[fname]["Index"]),
                "prefix": str(data[fname].get("Prefix", "")),
            })
        recs.append({
            "sym": name,
            "ordinal": int(r["Ordinal"]),
            "handler": str(r["PrinterHandler"]),
            "leaf": "true" if int(r["IsLeaf"]) else "false",
            "feature": str(r["RequiredFeature"]),
            "target": str(r.get("Target", "")),
            "model": str(r.get("Model", "")),
            "abbrev": str(r.get("Abbrev", "")),
            "layout": str(r.get("Layout", "")),
            "syntax": str(r.get("Syntax", "")),
            "closeSyntax": str(r.get("CloseSyntax", "")),
            "listField": str(r.get("ListField", "")),
            "listInner": str(r.get("ListInner", "")),
            "listOuter": str(r.get("ListOuter", "")),
            "generated": bool(int(r.get("GeneratedHandler", 0))),
            "fields": fields,
            "enumFields": enum_fields,
            "itemSyntax": str(r.get("ItemSyntax", "")),
            "itemFields": item_fields,
            "emptyItemSyntax": str(r.get("EmptyItemSyntax", "")),
        })
    # Deterministic total order — never the incidental record-emission order.
    recs.sort(key=lambda r: (r["model"], r["ordinal"], r["sym"]))
    validate_printer_records(recs)
    declarations = []
    for name in data.get("!instanceof", {}).get("TargetPrinterModel", []):
        r = data[name]
        declarations.append({
            "target": str(r.get("Target", "")),
            "model": str(r.get("Model", "")),
            "abbrev": str(r.get("Abbrev", "")),
            "primary": bool(int(r.get("Primary", 0))),
        })
    declarations.sort(key=lambda r: (r["target"], r["model"], r["abbrev"], r["primary"]))
    # Standalone (mode, role) -> atom idiom rows ( G1-S1): the status-authority
    # lowering table a legalizer consumes with the PROJECTED (ExecutionMode,
    # LifecycleRole). No printer node spells status; the generator emits the table
    # and its accessor so the legalizer reads a role's atom instead of writing it
    # inline. Validated here (producer path) so a bad row fails before it can
    # regenerate a vacuous or shadowed accessor.
    status_atoms = []
    for name in data.get("!instanceof", {}).get("LifecycleAtom", []):
        r = data[name]
        status_atoms.append({
            "mode": str(r["Mode"]),
            "role": str(r["Role"]),
            "atom": str(r["Atom"]),
        })
    status_atoms.sort(key=lambda a: (a["mode"], a["role"]))
    validate_status_atoms(status_atoms)
    return recs, declarations, status_atoms


# The CLOSED projection enum symbols a `LifecycleAtom` row may key on — kept in
# lockstep with include/Neutrino/BackendProjection.h (`ExecutionMode` /
# `LifecycleRole`). The regeneration freshness gate + the C++ compile of the
# generated `<backend>StatusAtom` accessor catch any drift from those enums.
STATUS_ATOM_MODES = ("Evidence", "Effectful", "Temporal")
STATUS_ATOM_ROLES = ("Initial", "AcceptedOrAttested", "Success")


def validate_status_atoms(rows):
    """Validate the standalone (mode, role) -> atom idiom rows ( G1-S1 P1-2).

    The status-authority table is consumed with a PROJECTED (mode, role), so a
    row keyed on an unknown mode/role symbol, carrying an empty atom, or
    duplicating a (mode, role) key would silently mis-lower or shadow a real
    mapping. Each is a producer-path failure — the generated accessor must be a
    total, unambiguous function of a valid closed key.
    """
    seen = set()
    for r in rows:
        if r["mode"] not in STATUS_ATOM_MODES:
            sys.exit("gen_target_node_registry: LifecycleAtom has unknown mode "
                     f"{r['mode']!r} (expected one of {STATUS_ATOM_MODES})")
        if r["role"] not in STATUS_ATOM_ROLES:
            sys.exit("gen_target_node_registry: LifecycleAtom has unknown role "
                     f"{r['role']!r} (expected one of {STATUS_ATOM_ROLES})")
        if not r["atom"]:
            sys.exit("gen_target_node_registry: LifecycleAtom "
                     f"({r['mode']}, {r['role']}) has an empty atom")
        key = (r["mode"], r["role"])
        if key in seen:
            sys.exit("gen_target_node_registry: LifecycleAtom has duplicate "
                     f"(mode, role) key {key}")
        seen.add(key)


def validate_printer_records(recs):
    """Validate the source `.td` records before rendering generated handlers.

    This is deliberately on the producer path, not only in the consumer gate: a
    committed `.td` edit with missing syntax or bad field projection must fail
    before it can regenerate a vacuous handler.
    """
    placeholders_rx = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
    for r in recs:
        if not r["generated"]:
            continue
        sym = r["sym"]
        if not r["layout"]:
            sys.exit(f"gen_target_node_registry: generated record {sym} has empty Layout")
        if r["layout"] not in SUPPORTED_LAYOUTS:
            sys.exit(f"gen_target_node_registry: generated record {sym} has unsupported Layout {r['layout']!r}")
        # The `blank` layout is a fieldless empty line — it takes no syntax pattern and no fields; every
        # other layout must carry a non-empty syntax pattern.
        if r["layout"] == "blank":
            if r["syntax"] or r["closeSyntax"] or r["fields"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} has blank layout but a non-empty "
                         "Syntax/CloseSyntax/Fields (blank emits an empty line only)")
        elif not r["syntax"]:
            sys.exit(f"gen_target_node_registry: generated record {sym} has empty Syntax")
        if r["layout"] in NESTING_LAYOUTS and not r["closeSyntax"]:
            sys.exit(f"gen_target_node_registry: generated record {sym} has {r['layout']} layout but empty CloseSyntax")
        # `block`/`flat-block` use CloseSyntax as their close delimiter;
        # `framed-lines` uses it as the fixed FOOTER. No other layout may carry
        # CloseSyntax.
        if r["layout"] not in (NESTING_LAYOUTS | {"framed-lines"}) and r["closeSyntax"]:
            sys.exit(f"gen_target_node_registry: generated record {sym} has CloseSyntax but is not a block/flat-block/framed-lines layout")
        # FRAMED-LINES (): a fixed HEADER (Syntax) + one repeated ItemSyntax +
        # a fixed FOOTER (CloseSyntax). ItemSyntax is ONLY for framed-lines.
        placeholder_names = lambda s: placeholders_rx.findall(s)
        if r["layout"] == "framed-lines":
            if not r["itemSyntax"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} has framed-lines layout but empty ItemSyntax")
            # A framed-lines node always has a fixed HEADER. CloseSyntax is an
            # optional fixed FOOTER for header-only repeated containers.
            # Item-field Prefix uses the normal optional-scalar contract.
            # Header/footer are FIXED literal shape — no projection (the decision
            # stays upstream). Only ItemSyntax projects, and only its item fields.
            if placeholder_names(r["syntax"]) or placeholder_names(r["closeSyntax"]):
                sys.exit(f"gen_target_node_registry: generated record {sym} framed-lines Header/Footer must be "
                         "fixed literal (no ${...} placeholders)")
            if r["fields"] or r["listField"] or r["enumFields"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} framed-lines node must not declare "
                         "scalar Fields / ListField / EnumFields (only ItemFields project, over the tuple)")
            item_names = [f["name"] for f in r["itemFields"]]
            dup_items = sorted({n for n in item_names if item_names.count(n) > 1})
            if dup_items:
                sys.exit(f"gen_target_node_registry: generated record {sym} has duplicate item field(s) {dup_items}")
            item_idxs = sorted(f["index"] for f in r["itemFields"])
            if not item_idxs or item_idxs != list(range(len(item_idxs))):
                sys.exit(f"gen_target_node_registry: generated record {sym} item field indices {item_idxs} are not a "
                         f"dense 0..N-1 range (each tuple slot projected exactly once)")
            refs = placeholder_names(r["itemSyntax"])
            if not refs:
                sys.exit(f"gen_target_node_registry: generated record {sym} ItemSyntax has no ${{item field}} placeholder")
            undeclared = [n for n in refs if n not in item_names]
            if undeclared:
                sys.exit(f"gen_target_node_registry: generated record {sym} ItemSyntax references undeclared item field(s) {sorted(set(undeclared))}")
            unref = sorted(set(item_names) - set(refs))
            if unref:
                sys.exit(f"gen_target_node_registry: generated record {sym} declares item field(s) {unref} not referenced in ItemSyntax")
            # An empty-case placeholder is verbatim shape (no projection) and is
            # meaningful only for a repeated (framed-lines) section.
            if placeholder_names(r.get("emptyItemSyntax", "")):
                sys.exit(f"gen_target_node_registry: generated record {sym} EmptyItemSyntax must be a fixed line with no ${{...}} placeholder")
        else:
            if r["itemSyntax"] or r["itemFields"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} has ItemSyntax/ItemFields but is not a framed-lines layout")
            if r.get("emptyItemSyntax"):
                sys.exit(f"gen_target_node_registry: generated record {sym} has EmptyItemSyntax but is not a framed-lines layout")
        # The leaf/nesting contract must be internally consistent: a nesting
        # layout (`block`/`flat-block`) nests children (non-leaf); every other
        # layout is terminal (leaf). The driver re-checks this at runtime and
        # fails closed, but a `.td` that declares an inconsistent IsLeaf must
        # never regenerate in the first place.
        is_leaf = r["leaf"] == "true"
        if is_leaf == (r["layout"] in NESTING_LAYOUTS):
            sys.exit(f"gen_target_node_registry: generated record {sym} declares IsLeaf={r['leaf']} "
                     f"inconsistent with layout {r['layout']!r} (block/flat-block nest → non-leaf; else leaf)")
        names = [f["name"] for f in r["fields"]]
        dup_names = sorted({n for n in names if names.count(n) > 1})
        if dup_names:
            sys.exit(f"gen_target_node_registry: generated record {sym} has duplicate field(s) {dup_names}")
        bad_indices = sorted({f["index"] for f in r["fields"] if f["index"] < 0})
        if bad_indices:
            sys.exit(f"gen_target_node_registry: generated record {sym} has negative field index(es) "
                     f"{bad_indices}")
        # Arity-generic contract: a node projecting N distinct operands must bind
        # exactly operand indices 0..N-1 (dense, no gaps/dups), so the model's
        # operand list is fully and unambiguously consumed.
        idxs = sorted(f["index"] for f in r["fields"])
        if idxs and idxs != list(range(len(idxs))):
            sys.exit(f"gen_target_node_registry: generated record {sym} field indices {idxs} are not a "
                     f"dense 0..{len(idxs) - 1} range (each operand projected exactly once)")
        # A REPEATED-field (list) projection: `ListField` names a placeholder that
        # is NOT a scalar operand field — it expands the model's repeated group.
        # It must be a single non-empty name appearing (exactly once) in the
        # syntax, distinct from the scalar fields, and carry both inner + outer
        # delimiters; the close pattern never carries the list.
        list_field = r["listField"]
        if list_field:
            if list_field in names:
                sys.exit(f"gen_target_node_registry: generated record {sym} ListField {list_field!r} "
                         "collides with a scalar field name")
            if not r["listInner"] or not r["listOuter"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} declares ListField "
                         f"{list_field!r} but is missing ListInner/ListOuter delimiter(s)")
            if ("${" + list_field + "}") in r["closeSyntax"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} references the list field in "
                         "CloseSyntax (the list projects into the open pattern only)")
        elif r["listInner"] or r["listOuter"]:
            sys.exit(f"gen_target_node_registry: generated record {sym} declares ListInner/ListOuter "
                     "without a ListField")
        # ENUM fields (): each `${name}` spells a CLOSED ordinal->spelling
        # table. The name must be distinct from scalar/list fields, appear in the
        # OPEN syntax only, and carry a NON-EMPTY spelling list with no empty
        # spelling (fail closed on a missing mapping); a REPEATED enum needs a
        # non-empty inner separator, a scalar enum must not carry one.
        enum_names = [ef["name"] for ef in r["enumFields"]]
        if len(set(enum_names)) != len(enum_names):
            sys.exit(f"gen_target_node_registry: generated record {sym} has duplicate enum field name(s)")
        for ef in r["enumFields"]:
            if ef["name"] in names or ef["name"] == list_field:
                sys.exit(f"gen_target_node_registry: generated record {sym} enum field {ef['name']!r} "
                         "collides with a scalar/list field name")
            if not ef["spellings"] or any(s == "" for s in ef["spellings"]):
                sys.exit(f"gen_target_node_registry: generated record {sym} enum field {ef['name']!r} "
                         "has an empty or missing spelling (the vocabulary must be total)")
            if len(set(ef["spellings"])) != len(ef["spellings"]):
                sys.exit(f"gen_target_node_registry: generated record {sym} enum field {ef['name']!r} "
                         "has duplicate spelling(s) (the ordinal->spelling mapping must be injective)")
            # The C++ enum is GENERATED from Symbols ( review): symbols and
            # spellings are 1:1, every symbol a distinct C++ identifier — so the
            # enum member set is exactly this list and cannot alias/drift.
            if len(ef["symbols"]) != len(ef["spellings"]):
                sys.exit(f"gen_target_node_registry: generated record {sym} enum field {ef['name']!r} "
                         "has mismatched Symbols/Spellings lengths")
            if len(set(ef["symbols"])) != len(ef["symbols"]):
                sys.exit(f"gen_target_node_registry: generated record {sym} enum field {ef['name']!r} "
                         "has duplicate C++ symbol(s) (each enum member must be distinct)")
            for s in ef["symbols"]:
                if not re.fullmatch(r"[A-Za-z_]\w*", s) or s == "Count":
                    sys.exit(f"gen_target_node_registry: generated record {sym} enum field {ef['name']!r} "
                             f"has an invalid or reserved C++ symbol {s!r} (Count is the sentinel)")
            if ef["repeated"] and not ef["inner"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} repeated enum field "
                         f"{ef['name']!r} needs a non-empty Inner separator")
            if not ef["repeated"] and ef["inner"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} scalar enum field "
                         f"{ef['name']!r} may not carry an Inner separator")
            if ("${" + ef["name"] + "}") in r["closeSyntax"]:
                sys.exit(f"gen_target_node_registry: generated record {sym} references enum field "
                         f"{ef['name']!r} in CloseSyntax (enum fields project into the open pattern only)")
        placeholders = placeholders_rx.findall(r["syntax"] + " " + r["closeSyntax"])
        declared = set(names) | ({list_field} if list_field else set()) | set(enum_names)
        used = set(placeholders)
        undeclared = sorted(used - declared)
        if undeclared:
            sys.exit(f"gen_target_node_registry: generated record {sym} references undeclared field(s) "
                     f"{undeclared}")
        unused = sorted(declared - used)
        if unused:
            sys.exit(f"gen_target_node_registry: generated record {sym} declares unused field(s) {unused}")


def backend_identity(recs, declarations=()):
    """Derive the backend identity FROM THE RECORDS (registry-derived, not a CLI
    arg): the C++ namespace `<target>_model`, model types, and committed X-macro
    names. An explicit Primary role anchors multi-model reconciliation without
    depending on record order. Fail closed if the `.td` mixes targets or
    abbreviations or leaves an identity empty; one `.td` describes one backend
    with one or more models."""
    if not recs:
        sys.exit("gen_target_node_registry: no TargetPrinterNode records found in the .td")
    all_records = list(recs) + list(declarations)
    models = {r["model"] for r in all_records}
    abbrevs = {r["abbrev"] for r in recs}
    targets = {r["target"] for r in all_records}
    abbrevs = {r["abbrev"] for r in all_records}
    if len(targets) != 1 or not models or len(abbrevs) != 1:
        sys.exit("gen_target_node_registry: all records in one .td must share a single "
                 f"Target/Abbrev and declare at least one Model (got targets={sorted(targets)}, models={sorted(models)}, "
                 f"abbrevs={sorted(abbrevs)})")
    target, abbrev = targets.pop(), abbrevs.pop()
    if not (target and abbrev) or any(not model for model in models):
        sys.exit("gen_target_node_registry: Target, every Model, and Abbrev must all be non-empty")
    models = sorted(models)
    node_models = sorted({r["model"] for r in recs})
    primary_models = [r["model"] for r in declarations if r.get("primary")]
    if declarations:
        declared_models = {r["model"] for r in declarations}
        if declared_models != set(models) or len(primary_models) != 1:
            sys.exit("gen_target_node_registry: model declarations must cover every model "
                     "and select exactly one Primary model")
        primary_model = primary_models[0]
    elif len(node_models) == 1:
        primary_model = node_models[0]
    else:
        sys.exit("gen_target_node_registry: a multi-model backend must declare exactly one Primary model")
    return {
        "target": target,
        "model": primary_model,
        "models": models,
        "abbrev": abbrev,
        "namespace": f"{target}_model",
        "macro": f"NEU_{abbrev}_NODE",
    }


def _model_macro(backend, model):
    if len(backend["models"]) == 1:
        return backend["macro"]
    model_token = re.sub(r"[^A-Za-z0-9]", "_", model).upper()
    return f"NEU_{backend['abbrev']}_{model_token}_NODE"


def render(td, recs, backend):
    rel = os.path.relpath(td, REPO)
    gen = os.path.relpath(os.path.abspath(__file__), REPO)
    lines = [
        f"// GENERATED from {rel} by {gen} — DO NOT EDIT.",
        "// Regenerate: `make regen-target-node-registry` (or run the generator).",
        "// The check_target_node_registry.py gate fails if this is stale or hand-edited.",
    ]
    if len(backend["models"]) > 1:
        lines.append("//   Model-qualified X-macros keep disjoint carrier enums disjoint.")
    for model in backend["models"]:
        macro = _model_macro(backend, model)
        label = f"{model}: {macro}" if len(backend["models"]) > 1 else f"X-macro: {macro}"
        lines += [
            f"//   {label}(Sym, Ordinal, Handler, IsLeaf, Feature)",
            f"#ifndef {macro}",
            f"#define {macro}(Sym, Ordinal, Handler, IsLeaf, Feature)",
            "#endif",
        ]
        for r in recs:
            if r["model"] == model:
                lines.append(
                    f'{macro}({r["sym"]}, {r["ordinal"]}, "{r["handler"]}", {r["leaf"]}, "{r["feature"]}")'
                )
        lines.append(f"#undef {macro}")
    return "\n".join(lines) + "\n"


def _cpp(s):
    # C-escape for a double-quoted string literal: backslash and quote, plus the
    # line terminators a `lines` layout carries (a multi-line Syntax holds real
    # `\n`/`\r`; unescaped, they would break the emitted string literal across
    # physical lines). A no-op for single-line syntax (no newline to escape).
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\n", "\\n").replace("\r", "\\r"))


def _layout(name):
    if name == "line":
        return "target_printer::LayoutKind::Line"
    if name == "commented-line":
        return "target_printer::LayoutKind::CommentedLine"
    if name == "blank":
        return "target_printer::LayoutKind::Blank"
    if name == "block":
        return "target_printer::LayoutKind::Block"
    if name == "flat-block":
        return "target_printer::LayoutKind::FlatBlock"
    if name == "lines":
        return "target_printer::LayoutKind::Lines"
    if name == "framed-lines":
        return "target_printer::LayoutKind::FramedLines"
    sys.exit(f"gen_target_node_registry: unsupported generated layout {name!r}")


def render_printer(td, recs, backend):
    ns = backend["namespace"]
    # Capitalized display label for the fail-closed messages ("solidity" ->
    # "Solidity"), so the emitted diagnostics are backend-derived, not hardcoded.
    label = backend["target"].capitalize()
    rel = os.path.relpath(td, REPO)
    gen = os.path.relpath(os.path.abspath(__file__), REPO)
    generated = [r for r in recs if r["generated"]]
    lines = [
        f"// GENERATED from {rel} by {gen} — DO NOT EDIT.",
        "// Regenerate: `make regen-target-node-registry` (or run the generator).",
        "// Shared generated target-printer handlers ().",
        "#include \"Neutrino/TargetPrinter.h\"",
        "#include \"llvm/Support/ErrorHandling.h\"",
        "#include <optional>",
        "#include <utility>",
        "#include <vector>",
        "",
        "namespace neutrino {",
        f"namespace {ns} {{",
        "namespace generated_printer {",
        "",
        "namespace target_printer = ::neutrino::target_printer;",
        "",
    ]
    multi_model = len(backend["models"]) > 1

    def stem(r):
        return f"{r['model']}{r['sym']}" if multi_model else r["sym"]

    def model_stem(model):
        return model if multi_model else ""

    for r in generated:
        fields = r["fields"]
        # A zero-field record emits no array: an empty C-style array is a GNU
        # extension, while its handler already selects nullptr below.
        if not fields:
            continue
        lines.append(f"inline constexpr target_printer::FieldBinding k{stem(r)}Fields[] = {{")
        for f in fields:
            prefix = f'"{_cpp(f["prefix"])}"' if f.get("prefix") else "nullptr"
            lines.append(f'  {{"{_cpp(f["name"])}", {f["index"]}, {prefix} }},')
        lines.append("};")
        lines.append("")
    # Each referenced enum SPELLING table is emitted ONCE (ordinal -> literal
    # target spelling) with its member count — the single declarative source the
    # model enum's member count must match (the coverage check keys on it).
    seen_spellings = {}
    for r in generated:
        for ef in r["enumFields"]:
            seen_spellings[ef["spellingSym"]] = ef["spellings"]
    for spname, spellings in sorted(seen_spellings.items()):
        lines.append(f"inline constexpr const char *k{spname}[] = {{")
        for s in spellings:
            lines.append(f'  "{_cpp(s)}",')
        lines.append("};")
        lines.append(f"inline constexpr std::size_t k{spname}Count = {len(spellings)};")
        lines.append("")
    # Per-node ENUM-field descriptor arrays: {name, spellings, count, repeated,
    # inner, prefix, groupIndex}. groupIndex is the field's position, matching the
    # model's enum-ordinal group order.
    for r in generated:
        if not r["enumFields"]:
            continue
        lines.append(f"inline constexpr target_printer::EnumField k{stem(r)}Enums[] = {{")
        for i, ef in enumerate(r["enumFields"]):
            inner = f'"{_cpp(ef["inner"])}"' if ef["inner"] else "nullptr"
            prefix = f'"{_cpp(ef["prefix"])}"' if ef["prefix"] else "nullptr"
            rep = "true" if ef["repeated"] else "false"
            lines.append(
                f'  {{"{_cpp(ef["name"])}", k{ef["spellingSym"]}, k{ef["spellingSym"]}Count, '
                f'{rep}, {inner}, {prefix}, {i} }},')
        lines.append("};")
        lines.append("")
    # Per-node FRAMED-LINES item-field arrays: the `${name}` bindings the repeated
    # ItemSyntax projects from each model tuple (dense per-item arity). Emitted only
    # for a framed-lines node with item fields (an empty array is a GNU extension).
    for r in generated:
        if not r["itemFields"]:
            continue
        lines.append(f"inline constexpr target_printer::FieldBinding k{stem(r)}ItemFields[] = {{")
        for f in r["itemFields"]:
            prefix = f'"{_cpp(f["prefix"])}"' if f.get("prefix") else "nullptr"
            lines.append(f'  {{"{_cpp(f["name"])}", {f["index"]}, {prefix} }},')
        lines.append("};")
        lines.append("")
    for model in backend["models"]:
        model_recs = [r for r in generated if r["model"] == model]
        if not model_recs:
            continue
        prefix = model_stem(model)
        lines.append(f"inline constexpr target_printer::Handler k{prefix}Handlers[] = {{")
        for r in model_recs:
            field_name = f"k{stem(r)}Fields" if r["fields"] else "nullptr"
            # The optional repeated-field (list) projection: a C-string name +
            # delimiters, or nullptr when the node has no list field.
            list_field = f'"{_cpp(r["listField"])}"' if r["listField"] else "nullptr"
            list_inner = f'"{_cpp(r["listInner"])}"' if r["listField"] else "nullptr"
            list_outer = f'"{_cpp(r["listOuter"])}"' if r["listField"] else "nullptr"
            enum_name = f"k{stem(r)}Enums" if r["enumFields"] else "nullptr"
            enum_count = len(r["enumFields"])
            # FRAMED-LINES: repeated item-line template + dense bindings + an
            # optional empty-case placeholder line.
            item_syntax = f'"{_cpp(r["itemSyntax"])}"' if r["itemSyntax"] else "nullptr"
            item_field_name = f"k{stem(r)}ItemFields" if r["itemFields"] else "nullptr"
            empty_item = f'"{_cpp(r["emptyItemSyntax"])}"' if r.get("emptyItemSyntax") else "nullptr"
            lines.append(
                f'  {{{r["ordinal"]}, "{_cpp(r["target"])}", "{_cpp(r["sym"])}", '
                f'"{_cpp(r["handler"])}", {_layout(r["layout"])}, {r["leaf"]}, '
                f'"{_cpp(r["syntax"])}", "{_cpp(r["closeSyntax"])}", {field_name}, {len(r["fields"])}, '
                f'{list_field}, {list_inner}, {list_outer}, {enum_name}, {enum_count}, '
                f'{item_syntax}, {item_field_name}, {len(r["itemFields"])}, {empty_item} }},'
            )
        lines.append("};")
        lines.append("")

        lines.append(f"inline const target_printer::Handler *handlerFor({model}::Kind kind) {{")
        lines.append("  int ordinal = static_cast<int>(kind);")
        lines.append(f"  for (const auto &handler : k{prefix}Handlers)")
        lines.append("    if (handler.ordinal == ordinal)")
        lines.append("      return &handler;")
        lines.append("  return nullptr;")
        lines.append("}")
        lines.append("")
        lines.append(f"inline bool hasHandler({model}::Kind kind) {{ return handlerFor(kind) != nullptr; }}")
        lines.append("")
        lines.append(f"inline std::string resolve{prefix}Field(const void *model, unsigned index) {{")
        variable = "node" if multi_model else "stmt"
        if not multi_model:
            lines.append("  // Arity-generic projection: return the model operand at `index`,")
            lines.append("  // failing closed on an out-of-range index (never silently empty).")
        lines.append(f"  const {model} &{variable} = *static_cast<const {model} *>(model);")
        lines.append(f"  if (index >= {variable}.operands.size())")
        diagnostic_model = f" {model}" if multi_model else ""
        lines.append(f'    llvm::report_fatal_error("target-printer: {label}{diagnostic_model} field index out of range",')
        lines.append("                             /*gen_crash_diag=*/false);")
        lines.append(f"  return {variable}.operands[index];")
        lines.append("}")
        lines.append("")
        has_group = any(r["listField"] or r["layout"] == "framed-lines" for r in model_recs)
        if has_group:
            lines.append("inline const std::vector<std::vector<std::string>> &")
            lines.append(f"resolve{prefix}Groups(const void *model) {{")
            lines.append(f"  return static_cast<const {model} *>(model)->group;")
            lines.append("}")
            lines.append("")
        resolve_groups_arg = f"resolve{prefix}Groups" if has_group else "nullptr"
        has_enum = any(r["enumFields"] for r in model_recs)
        if has_enum:
            lines.append("inline const std::vector<std::vector<int>> &")
            lines.append(f"resolve{prefix}Enums(const void *model) {{")
            lines.append(f"  return static_cast<const {model} *>(model)->enumOrdinals;")
            lines.append("}")
            lines.append("")
        resolve_enums_arg = f"resolve{prefix}Enums" if has_enum else "nullptr"
        lines.append(f"inline codetext::Node render(const {model} &{variable},")
        lines.append("                            std::vector<codetext::Node> children = {},")
        lines.append("                            std::optional<target_printer::CommentedLineData>")
        lines.append("                                commentedLine = std::nullopt) {")
        lines.append(f"  const target_printer::Handler *handler = handlerFor({variable}.kind);")
        lines.append("  if (!handler)")
        handler_model = f" {model}" if multi_model else ""
        lines.append(f'    llvm::report_fatal_error("target-printer: no generated {label}{handler_model} handler",')
        lines.append("                             /*gen_crash_diag=*/false);")
        lines.append(f"  return target_printer::render(*handler, &{variable}, resolve{prefix}Field,")
        lines.append(f"                                {variable}.operands.size(), std::move(children),")
        lines.append(f"                                {resolve_groups_arg}, {resolve_enums_arg},")
        lines.append("                                std::move(commentedLine));")
        lines.append("}")
        lines.append("")
    lines.append("} // namespace generated_printer")
    lines.append(f"}} // namespace {ns}")
    lines.append("} // namespace neutrino")
    return "\n".join(lines) + "\n"


def _enum_types(recs):
    """The distinct closed enums `cppType -> (ordered symbols, ordered spellings)`,
    from every generated record's enum fields, in first-seen order. Fails closed
    if the same cppType is declared with conflicting members or spellings."""
    seen = {}

    def add(ct, symbols, spellings):
        if ct in seen and seen[ct] != (symbols, spellings):
            sys.exit(f"gen_target_node_registry: enum type {ct!r} declared with "
                     "conflicting members/spellings")
        seen[ct] = (symbols, spellings)

    for r in recs:
        if not r["generated"]:
            continue
        for ef in r["enumFields"]:
            add(ef["cppType"], ef["symbols"], ef["spellings"])
    return seen


def render_enums(td, recs, backend, status_atoms=()):
    """The GENERATED C++ enum X-macro source ( review): the SINGLE source for
    each closed model enum. Included by the backend model header to define
    `enum class <CppType> { <Symbol> = <ordinal>, …, Count }`, and by the coverage
    check to build a position probe + per-member ordinal assertions. Because the
    enum members ARE this list (position-indexed), an added member cannot alias an
    existing ordinal, and a hand-edit is caught by the regeneration freshness gate
    and the generated position asserts. The standalone status-authority idiom
    ( G1-S1) is emitted here too, as a `NEU_<Abbrev>_STATUS_ATOM(ModeSym,
    RoleSym, Atom)` X-macro the `<backend>StatusAtom(mode, role)` accessor reads,
    so a legalizer spells a projected role's atom without an inline literal."""
    enum_types = _enum_types(recs)
    if not enum_types and not status_atoms:
        return None  # a backend with no closed enums / idiom emits no enum source
    macro = f"NEU_{backend['abbrev']}_ENUM_"
    rel = os.path.relpath(td, REPO)
    gen = os.path.relpath(os.path.abspath(__file__), REPO)
    lines = [
        f"// GENERATED from {rel} by {gen} — DO NOT EDIT.",
        "// Regenerate: `make regen-target-node-registry` (or run the generator).",
        "// Closed model enums (): X-macro member lists, one guarded block per",
        f"// enum. Define {macro}<CppType>(Sym, Ordinal, Spelling) then include.",
        "",
    ]
    for ct, (symbols, spellings) in enum_types.items():
        lines.append(f"#ifdef {macro}{ct}")
        for i, (sym, spell) in enumerate(zip(symbols, spellings)):
            lines.append(f'{macro}{ct}({sym}, {i}, "{_cpp(spell)}")')
        lines.append(f"#endif // {macro}{ct}")
        lines.append("")
    # The standalone status-authority (mode, role) -> atom idiom ( G1-S1),
    # sorted by (mode, role). The accessor consumes the PROJECTED (mode, role).
    if status_atoms:
        atom_macro = f"NEU_{backend['abbrev']}_STATUS_ATOM"
        lines.append(f"#ifdef {atom_macro}")
        for a in status_atoms:
            lines.append(f'{atom_macro}({a["mode"]}, {a["role"]}, "{_cpp(a["atom"])}")')
        lines.append(f"#endif // {atom_macro}")
        lines.append("")
    # Exactly one terminal newline (the per-block trailing blank would otherwise
    # leave a blank line at EOF — `git diff --check` flags it).
    return "\n".join(lines).rstrip("\n") + "\n"


def main():
    ap = argparse.ArgumentParser(description="target-node metadata registry generator ()")
    ap.add_argument("--td", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--printer-out", default=None)
    ap.add_argument("--enums-out", default=None,
                    help="also emit the generated C++ enum X-macro source ()")
    ap.add_argument("--tblgen", default=None)
    ap.add_argument("--check", action="store_true",
                    help="compare regenerated output to --out; exit 1 if stale (do not write)")
    args = ap.parse_args()
    recs, declarations, status_atoms = records(args.td, find_tblgen(args.tblgen))
    # The target/model/X-macro are REGISTRY-DERIVED from the record fields (not a
    # CLI arg): the namespace is `<Target>_model`, the model type is `Model`, and
    # the committed X-macro name is `NEU_<Abbrev>_NODE`.
    backend = backend_identity(recs, declarations)
    text = render(args.td, recs, backend)
    printer_text = render_printer(args.td, recs, backend) if args.printer_out else None
    enums_text = render_enums(args.td, recs, backend, status_atoms) if args.enums_out else None
    if args.check:
        cur = open(args.out, encoding="utf-8").read() if os.path.isfile(args.out) else ""
        if cur != text:
            print(f"STALE: {args.out} is out of date with {args.td} — run `make regen-target-node-registry`",
                  file=sys.stderr)
            return 1
        if args.printer_out:
            cur = open(args.printer_out, encoding="utf-8").read() if os.path.isfile(args.printer_out) else ""
            if cur != printer_text:
                print(f"STALE: {args.printer_out} is out of date with {args.td} — run `make regen-target-node-registry`",
                      file=sys.stderr)
                return 1
        if args.enums_out and enums_text is not None:
            cur = open(args.enums_out, encoding="utf-8").read() if os.path.isfile(args.enums_out) else ""
            if cur != enums_text:
                print(f"STALE: {args.enums_out} is out of date with {args.td} — run `make regen-target-node-registry`",
                      file=sys.stderr)
                return 1
        return 0
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    if args.printer_out:
        with open(args.printer_out, "w", encoding="utf-8") as f:
            f.write(printer_text)
        print(f"wrote {args.printer_out} ({len(printer_text.splitlines())} lines)")
    if args.enums_out and enums_text is not None:
        with open(args.enums_out, "w", encoding="utf-8") as f:
            f.write(enums_text)
        print(f"wrote {args.enums_out} ({len(enums_text.splitlines())} lines)")
    print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
