#!/usr/bin/env python3
"""Package the generated `.neu` grammar as GitHub/Linguist assets (M5  T3, ).

This does NOT create a second grammar — it PACKAGES the one generated by
(`docs/neutrino.tmLanguage.json`, itself generated from the compiler's
`docs/language-metadata.json`) into a self-contained `linguist/` bundle a
GitHub/Linguist-style consumer can use:

- `linguist/neutrino.tmLanguage.json` — a byte-for-byte COPY of the generated grammar
  (drift-gated to equal `docs/neutrino.tmLanguage.json`; never hand-edited).
- `linguist/languages.yml` — the Linguist language entry, DERIVED from the compiler
  metadata + grammar (name, `.neu` extension, `tm_scope`); the Linguist-submission
  presentation constants (type / color / ace_mode / provisional `language_id`) are owned
  here. This is the exact entry an upstream `github-linguist` PR needs.

Local/VS Code highlighting works from the grammar today; GitHub-web highlighting needs the
upstream Linguist merge (gated on their external usage threshold) — a tracked follow-up, NOT
an M5 blocker. See linguist/README.md.

Usage:
  generate_linguist_assets.py            # print languages.yml (from the committed metadata + grammar)
  generate_linguist_assets.py --write    # (re)write the linguist/ package
  generate_linguist_assets.py --check     # drift gate: packaged grammar == generated; languages.yml fresh
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
METADATA = os.path.join(REPO, "docs", "language-metadata.json")
GRAMMAR = os.path.join(REPO, "docs", "neutrino.tmLanguage.json")
PKG_DIR = os.path.join(REPO, "linguist")
PKG_GRAMMAR = os.path.join(PKG_DIR, "neutrino.tmLanguage.json")
PKG_LANGUAGES = os.path.join(PKG_DIR, "languages.yml")

# Linguist-submission presentation constants (owned here, not the compiler's — like the
# grammar generator owns TextMate scope names). `language_id` is PROVISIONAL: Linguist
# maintainers assign the real, globally-unique id at upstream merge (linguist/README.md).
LINGUIST_TYPE = "programming"
LINGUIST_COLOR = "6bfb"
LINGUIST_ACE_MODE = "text"
LINGUIST_LANGUAGE_ID_PROVISIONAL = 999900001


def _fail(msg):
    print(f"generate_linguist_assets: {msg}", file=sys.stderr)
    sys.exit(1)


def _load():
    try:
        m = json.load(open(METADATA))
        g = json.load(open(GRAMMAR))
    except (OSError, ValueError) as e:
        _fail(f"cannot read the generated metadata/grammar: {e}")
    if m.get("kind") != "neutrino.language-metadata":
        _fail("docs/language-metadata.json is not neutrino.language-metadata")
    return m, g


def languages_yml(m, g):
    """The Linguist language entry, derived from the compiler metadata + grammar."""
    name = g.get("name") or (m.get("language") or "").capitalize()
    ext = m.get("canonicalExtension") or ""   # ".neu"
    scope = g.get("scopeName") or ""          # "source.neutrino"
    if not (name and ext.startswith(".") and scope):
        _fail("metadata/grammar missing name/extension/scopeName")
    return (
        "# Generated by scripts/generators/generate_linguist_assets.py () from the compiler's language\n"
        "# metadata (docs/language-metadata.json) + the generated grammar\n"
        "# (docs/neutrino.tmLanguage.json). Do NOT hand-edit — run `make linguist`. This is the\n"
        "# Linguist language entry to upstream to github-linguist; see linguist/README.md.\n"
        f"{name}:\n"
        f"  type: {LINGUIST_TYPE}\n"
        f'  color: "{LINGUIST_COLOR}"\n'
        "  extensions:\n"
        f'    - "{ext}"\n'
        f"  tm_scope: {scope}\n"
        f"  ace_mode: {LINGUIST_ACE_MODE}\n"
        f"  language_id: {LINGUIST_LANGUAGE_ID_PROVISIONAL}\n"
    )


def write_pkg():
    m, g = _load()
    os.makedirs(PKG_DIR, exist_ok=True)
    # packaged grammar = a byte copy of the generated grammar (single source; drift-gated).
    with open(GRAMMAR) as src, open(PKG_GRAMMAR, "w") as dst:
        dst.write(src.read())
    with open(PKG_LANGUAGES, "w") as f:
        f.write(languages_yml(m, g))
    print(f"wrote {os.path.relpath(PKG_GRAMMAR, REPO)} + {os.path.relpath(PKG_LANGUAGES, REPO)}")


def check():
    m, g = _load()
    # 1. packaged grammar must be a byte-identical copy of the generated grammar (no hand-edit).
    if not os.path.exists(PKG_GRAMMAR):
        _fail("linguist/neutrino.tmLanguage.json is missing (run: make linguist)")
    if open(PKG_GRAMMAR).read() != open(GRAMMAR).read():
        _fail("linguist/neutrino.tmLanguage.json is STALE — it must byte-equal the generated "
              "docs/neutrino.tmLanguage.json; run `make linguist`")
    # 2. languages.yml must byte-match a fresh regeneration (derived from metadata + grammar).
    if not os.path.exists(PKG_LANGUAGES):
        _fail("linguist/languages.yml is missing (run: make linguist)")
    if open(PKG_LANGUAGES).read() != languages_yml(m, g):
        _fail("linguist/languages.yml is STALE — regenerate: make linguist")
    # 3. it must parse and carry the compiler-derived fields (a broken entry is fail-closed).
    try:
        import yaml
        entry = yaml.safe_load(open(PKG_LANGUAGES))
    except Exception as e:  # pyyaml present in CI; if truly absent, fail closed rather than skip
        _fail(f"could not parse linguist/languages.yml: {e}")
    name = g.get("name") or m["language"].capitalize()
    e = (entry or {}).get(name)
    if not e or e.get("tm_scope") != g["scopeName"] or m["canonicalExtension"] not in e.get("extensions", []):
        _fail(f"linguist/languages.yml '{name}' entry does not match the grammar scope / .neu extension")
    print(f"linguist assets OK: packaged grammar byte-equals the generated grammar; languages.yml "
          f"is fresh and its '{name}' entry maps {m['canonicalExtension']} -> {g['scopeName']}")


def main():
    ap = argparse.ArgumentParser(description="Package the generated .neu grammar as Linguist assets ()")
    ap.add_argument("--write", action="store_true", help="(re)write the linguist/ package")
    ap.add_argument("--check", action="store_true", help="drift gate (packaged==generated; languages.yml fresh)")
    args = ap.parse_args()
    if args.write:
        write_pkg()
    elif args.check:
        check()
    else:
        m, g = _load()
        sys.stdout.write(languages_yml(m, g))


if __name__ == "__main__":
    main()
