# [/] Prove a typed shell .td syntax record drives production output by
# RENDERING through both the committed and the .td-mutated generated handler:
#   * the COMMITTED handler must reproduce the golden line (exit 0);
#   * the MUTATED handler must NOT (exit != 0) and its render must carry the
#     node-specific mutated form, so the failure is caused by the syntax-record
#     mutation, not a crash.
# NODE selects the expected mutated render (LocalDecl 2a / Assign 2b via `:=`,
# CompoundAssign 2c via `/*mut*/`, DocComment  via `///x`).
#
# Invoked as a CTest:
#   cmake -DNODE=LocalDecl|Assign|CompoundAssign|DocComment \
#         -DCOMMITTED=<exe> -DMUTATED=<exe> -DGOLDEN=<.sol> -P this

if(NODE STREQUAL "InterfaceShell")
  set(_mutated_expect "interfacex IThresholdQuorumAcceptance {")
elseif(NODE STREQUAL "InterfaceSignature")
  set(_mutated_expect "function isAccepted(bytes32 claimId) external view returnsx (bool);")
elseif(NODE STREQUAL "ContractShell")
  # The container keyword `contract` -> `contractx` re-spells the block-open line.
  set(_mutated_expect "contractx CoreSupplyIssue {")
elseif(NODE STREQUAL "FunctionSig")
  # The callable-kind spelling `function` -> `functionx` re-spells the block-open
  # line, proving the enum SPELLING is `.td`-owned.
  set(_mutated_expect "functionx attest(string calldata u_transfer_id) external {")
elseif(NODE STREQUAL "EventDecl")
  set(_mutated_expect "eventx SenderDebitDebited(string party, uint256 amount, string currency);")
elseif(NODE STREQUAL "StorageDecl")
  set(_mutated_expect "mapping(bytes32 => Status) public statusOf /*mut*/;")
elseif(NODE STREQUAL "EnumDecl")
  set(_mutated_expect "enumx Status { None, Reconciled }")
elseif(NODE STREQUAL "Import")
  set(_mutated_expect "importx \"./CoordinationEnvelope.sol\";")
elseif(NODE STREQUAL "Pragma")
  set(_mutated_expect "pragmax solidity ^0.8.20;")
elseif(NODE STREQUAL "SpdxLicense")
  set(_mutated_expect "//x SPDX-License-Identifier: MIT")
elseif(NODE STREQUAL "DocComment")
  set(_mutated_expect "///x Generated by the Neutrino Translator from verified MLIR.")
elseif(NODE STREQUAL "CompoundAssign")
  set(_mutated_expect "debitTotal[_k] += u_amount /*mut*/;")
elseif(NODE STREQUAL "Assign")
  set(_mutated_expect "attested[_k] := true;")
else()
  set(_mutated_expect "bytes32 _k := keccak256(bytes(u_shipment_ref));")
endif()

execute_process(COMMAND "${COMMITTED}" "${GOLDEN}"
  RESULT_VARIABLE _crc OUTPUT_VARIABLE _cout ERROR_VARIABLE _cerr)
if(NOT _crc EQUAL 0)
  message(FATAL_ERROR
    "${NODE} render pair: the COMMITTED generated handler did NOT reproduce the "
    "golden line (rc=${_crc}):\n${_cout}${_cerr}")
endif()

execute_process(COMMAND "${MUTATED}" "${GOLDEN}"
  RESULT_VARIABLE _mrc OUTPUT_VARIABLE _mout ERROR_VARIABLE _merr)
if(_mrc EQUAL 0)
  message(FATAL_ERROR
    "${NODE} render pair: the .td-MUTATED generated handler still reproduced the "
    "golden line — the syntax-record mutation did not change production "
    "output:\n${_mout}${_merr}")
endif()
# Non-vacuity: the mutated failure must be the `:=` render, not an unrelated crash.
string(FIND "${_mout}" "${_mutated_expect}" _idx)
if(_idx EQUAL -1)
  message(FATAL_ERROR
    "${NODE} render pair: the mutated handler failed but did NOT render the "
    "expected `:=` line (vacuous failure):\n${_mout}${_merr}")
endif()

message(STATUS
  "${NODE} render pair holds: committed handler renders the golden `=` line; "
  "the .td-mutated handler renders `:=` and fails the golden.")
