// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "../src/ShipmentEvidenceAnchor.sol";

interface Vm {
    function expectRevert(bytes calldata) external;
    function expectEmit(bool, bool, bool, bool) external;
}

contract MockQuorumGuard {
    mapping(bytes32 => bool) public accepted;
    function setAccepted(bytes32 claimId, bool v) external {
        accepted[claimId] = v;
    }
    function isAccepted(bytes32 claimId) external view returns (bool) {
        return accepted[claimId];
    }
}

/// Generated by the Neutrino Translator from scenario "shipment_evidence_anchor_happy_path".
contract ShipmentEvidenceAnchorTest {
    Vm constant vm = Vm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
    ShipmentEvidenceAnchor c;
    MockQuorumGuard guard;

    string constant SHIPMENT_REF = "shipment-il-it-001";
    string constant DELIVERY_PROOF = "sha256:0011223344556677889900aabbccddeeff0011223344556677889900aabbccdd";
    string constant SHIPMENT_REF_2 = "shipment-il-it-001-2";

    event ShipmentEvidenceAnchorAccepted(string shipment_ref);

    function setUp() public {
        guard = new MockQuorumGuard();
        c = new ShipmentEvidenceAnchor(address(guard));
    }

    function _key() internal pure returns (bytes32) {
        return keccak256(bytes(SHIPMENT_REF));
    }

    function test_accept_records_evidence_and_emits() public {
        bytes32 _k = _key();
        guard.setAccepted(keccak256(bytes(SHIPMENT_REF)), true);
        vm.expectEmit(true, true, true, true);
        emit ShipmentEvidenceAnchorAccepted(SHIPMENT_REF);
        c.accept(SHIPMENT_REF, DELIVERY_PROOF);
        require(uint256(c.statusOf(_k)) == uint256(ShipmentEvidenceAnchor.Status.Accepted), "accepted");
    }

    function test_replay_is_refused() public {
        bytes32 _k = _key();
        guard.setAccepted(keccak256(bytes(SHIPMENT_REF)), true);
        c.accept(SHIPMENT_REF, DELIVERY_PROOF);
        vm.expectRevert(bytes("replay"));
        c.accept(SHIPMENT_REF, DELIVERY_PROOF);
        require(uint256(c.statusOf(_k)) == uint256(ShipmentEvidenceAnchor.Status.Accepted), "still accepted");
    }

    function test_unaccepted_quorum_rejected() public {
        vm.expectRevert(bytes("quorum not accepted"));
        c.accept(SHIPMENT_REF, DELIVERY_PROOF);
    }

    function test_accepted_quorum_proceeds() public {
        bytes32 _k = _key();
        guard.setAccepted(keccak256(bytes(SHIPMENT_REF)), true);
        c.accept(SHIPMENT_REF, DELIVERY_PROOF);
        require(uint256(c.statusOf(_k)) == uint256(ShipmentEvidenceAnchor.Status.Accepted), "gated status");
    }

    function test_instances_are_isolated_per_key() public {
        guard.setAccepted(keccak256(bytes(SHIPMENT_REF)), true);
        c.accept(SHIPMENT_REF, DELIVERY_PROOF);
        guard.setAccepted(keccak256(bytes(SHIPMENT_REF_2)), true);
        c.accept(SHIPMENT_REF_2, DELIVERY_PROOF);
        // each instance key keeps its own status; no sharing
        require(uint256(c.statusOf(keccak256(bytes(SHIPMENT_REF)))) == uint256(ShipmentEvidenceAnchor.Status.Accepted), "k1 status");
        require(uint256(c.statusOf(keccak256(bytes(SHIPMENT_REF_2)))) == uint256(ShipmentEvidenceAnchor.Status.Accepted), "k2 status");
    }
}
