-- Generated by the Neutrino Translator from verified MLIR.
-- EVIDENCE-ONLY coordination: records accepted attested evidence by instance
-- key and moves NO ledger value. Idempotent + atomic (single transaction).
CREATE OR REPLACE FUNCTION accept_shipment_evidence_anchor(p_shipment_ref text, p_canonical_claim_hash text, p_observers text[])
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM quorum_acceptance WHERE claim_id = p_shipment_ref AND procedure = 'shipment_evidence_anchor') THEN
        RAISE EXCEPTION 'already accepted';
    END IF;
    IF EXISTS (SELECT 1 FROM unnest(p_observers) o(id) WHERE NOT EXISTS (SELECT 1 FROM authorized_observer a WHERE a.observer_set = 'logistics_oracles' AND a.observer_id = o.id)) THEN
        RAISE EXCEPTION 'unauthorized observer';
    END IF;
    IF (SELECT count(*) FROM unnest(p_observers)) <> (SELECT count(DISTINCT o.id) FROM unnest(p_observers) o(id)) THEN
        RAISE EXCEPTION 'duplicate observer';
    END IF;
    IF (SELECT count(DISTINCT o.id) FROM unnest(p_observers) o(id)) < 2 THEN
        RAISE EXCEPTION 'quorum not met';
    END IF;
    INSERT INTO quorum_acceptance(procedure, claim_id, canonical_claim_hash, observer_count)
    VALUES ('shipment_evidence_anchor', p_shipment_ref, p_canonical_claim_hash, (SELECT count(DISTINCT o.id) FROM unnest(p_observers) o(id)));
END;
$$;

CREATE OR REPLACE FUNCTION execute_shipment_evidence_anchor(p_shipment_ref text, p_delivery_proof text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM quorum_acceptance WHERE claim_id = p_shipment_ref AND procedure = 'shipment_evidence_anchor') THEN
        RAISE EXCEPTION 'quorum not accepted';
    END IF;

    -- Evidence-only: atomically CLAIM the accepted terminal; move NO ledger value.
    INSERT INTO coordination_status(procedure, idempotency_key, reconciled) VALUES ('shipment_evidence_anchor', p_shipment_ref, true)
    ON CONFLICT (procedure, idempotency_key) DO NOTHING;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'replay';
    END IF;
END;
$$;

-- Admission control (): accept_ is the quorum guard. Postgres grants EXECUTE to PUBLIC
-- by default and the observer ids are not secret, so a PUBLIC-callable accept_ is forgeable.
-- REVOKE it (no-access-by-default / fail-safe); the deployer MUST then GRANT it to ONLY the
-- off-chain aggregator role, e.g.:  GRANT EXECUTE ON FUNCTION accept_shipment_evidence_anchor(text, text, text[]) TO <aggregator_role>;
REVOKE EXECUTE ON FUNCTION accept_shipment_evidence_anchor(text, text, text[]) FROM PUBLIC;
