#!/usr/bin/env bash
# Validate the slot artifact-contract fixtures — every domain has the required
# slot files (now generated by `neutrino-gen --target=slot`, Phase 12), all are
# valid JSON, and each envelope.example.json (when present) conforms to that
# domain's envelope.schema.json. Scans BOTH layouts: legacy family-major
# (examples/slot/<domain>) and domain-major (examples/domains/<domain>/generated/slot, ).
#   scripts/validate-slot-fixtures.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
python3 - "$HERE" <<'PY'
import json, os, sys, glob
repo = sys.argv[1]
# required, generated by `neutrino-gen --target=slot`; envelope.example.json is an
# optional hand-written sample (validated against the schema only when present).
generated = ["capability.json", "operations.json", "compensation.json",
             "transcript.json", "envelope.schema.json", "capability.lock"]
fail = 0

# Slot fixture dirs across both layouts, labelled by their repo-relative path.
slot_dirs = []
legacy_root = os.path.join(repo, "examples", "slot")
if os.path.isdir(legacy_root):
    for d in sorted(os.listdir(legacy_root)):
        p = os.path.join(legacy_root, d)
        if os.path.isdir(p):
            slot_dirs.append((d, p))
for p in sorted(glob.glob(os.path.join(repo, "examples", "domains", "*", "generated", "slot"))):
    if os.path.isdir(p):
        dom = p.split(os.sep)[-3]
        slot_dirs.append((dom, p))

if not slot_dirs:
    print("FAIL: no slot domains found"); sys.exit(1)

try:
    from jsonschema import Draft7Validator
    have_js = True
except Exception:
    have_js = False
    print("note: jsonschema not installed — checking JSON validity + required fields only")

for d, dp in slot_dirs:
    label = os.path.relpath(dp, repo)
    ok = True
    for f in generated:
        p = os.path.join(dp, f)
        if not os.path.exists(p):
            print(f"  FAIL {label}: missing {f}"); fail += 1; ok = False; continue
        try:
            json.load(open(p))
        except Exception as e:
            print(f"  FAIL {label}/{f}: invalid JSON ({e})"); fail += 1; ok = False
    env_p = os.path.join(dp, "envelope.example.json")
    if os.path.exists(env_p):
        schema = json.load(open(os.path.join(dp, "envelope.schema.json")))
        try:
            env = json.load(open(env_p))
        except Exception as e:
            print(f"  FAIL {label}/envelope.example.json: invalid JSON ({e})"); fail += 1; ok = False
            env = None
        if env is not None:
            if have_js:
                errs = sorted(Draft7Validator(schema).iter_errors(env), key=str)
                if errs:
                    print(f"  FAIL {label}/envelope.example.json: " + "; ".join(e.message for e in errs[:3]))
                    fail += 1; ok = False
            else:
                missing = [k for k in schema["required"] if k not in env]
                if missing:
                    print(f"  FAIL {label}/envelope.example.json: missing {missing}"); fail += 1; ok = False
        env_note = "envelope valid against its schema"
    else:
        env_note = "no envelope.example.json (optional)"
    if ok:
        print(f"  ok   {label} (generated slot files present; {env_note})")

print()
if fail:
    print(f"SLOT FIXTURES FAILED ({fail})"); sys.exit(1)
print("SLOT FIXTURES PASSED")
PY
