//===- neutrino-bundle - run an agent input bundle -> output bundle
//--------===//
//
// The agent-facing entry point (Phase 8). It consumes a deterministic *input
// bundle* directory:
//
//   <in>/source.neu       the DSL source
//   <in>/scenario.json    concrete inputs + expected semantics
//   <in>/target.json      { "targets": ["solidity", "postgres"] }
//
// and produces an *output bundle* directory:
//
//   <out>/<target>/...    per-target artifacts + manifest.json +
//   diagnostics.json <out>/bundle.json     top-level result: input hashes +
//   per-target outcomes
//
// Each target is generated by invoking the `generate.<target>` capability
// (neutrino-gen), keeping the toolchain file-based and deterministic: the same
// input bundle always yields the same output bundle. The path to neutrino-gen
// comes from $NEUTRINO_GEN (else "neutrino-gen" on PATH).
//
//   neutrino-bundle <input-bundle-dir> -o <output-bundle-dir>
//   neutrino-bundle --capabilities          # print the capability descriptor
//
//===----------------------------------------------------------------------===//

#include "Neutrino/BackendDispatchReceipt.h"
#include "Neutrino/BackendInvoker.h"
#include "Neutrino/Diagnostics.h"
#include "Neutrino/Manifest.h"
#include "Neutrino/TargetCatalog.h"
#include "Neutrino/VersionInfo.h"

#include "llvm/Support/CommandLine.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"

#include <cctype>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <string>
#include <sys/wait.h>
#include <vector>

using namespace llvm;

static cl::opt<std::string> inDir(cl::Positional,
                                  cl::desc("<input-bundle-dir>"));
static cl::opt<std::string> outDir("o", cl::desc("output bundle directory"),
                                   cl::init("build/bundle"));
static cl::opt<bool>
    showCaps("capabilities",
             cl::desc("print the capability descriptor and exit"));
static cl::list<std::string> backendPackageDirectories(
    "backend-package-dir",
    cl::desc("verified external backend package directory (repeatable)"),
    cl::ZeroOrMore);

// Stable exit codes (shared with neutrino-gen where they overlap).
enum ExitCode {
  EXIT_OK = 0,
  EXIT_FAILED = 1, // a requested target failed generation
  EXIT_USAGE = 2,  // bad arguments / IO / parse error
};

namespace {

const char *kToolVersion =
    neutrino::kToolVersion; // single source: VersionInfo.h ()

std::string capabilitiesDescriptor(const neutrino::TargetCatalog &catalog) {
  json::Array capabilities;
  capabilities.push_back(
      json::Object{{"name", "translate.mlir"}, {"tool", "neutrino-translate"}});
  for (const neutrino::CatalogTarget &target : catalog.targets())
    capabilities.push_back(json::Object{
        {"name", "generate." + target.name},
        {"tool", "neutrino-gen --target=" + target.name},
    });
  json::Object root{
      {"capabilities", std::move(capabilities)},
      {"catalogIdentity", catalog.identity()},
      {"tool", "neutrino-bundle"},
      {"version", kToolVersion},
  };
  return formatv("{0:2}", json::Value(std::move(root))).str() + "\n";
}

// Wall-clock time, unless SOURCE_DATE_EPOCH pins it (so a caller that needs a
// byte-stable output bundle can fix the one non-deterministic field).
std::string isoNow() {
  std::time_t t = std::time(nullptr);
  if (const char *e = getenv("SOURCE_DATE_EPOCH"))
    t = static_cast<std::time_t>(std::strtoll(e, nullptr, 10));
  char buf[32];
  if (std::strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%SZ", std::gmtime(&t)) ==
      0)
    buf[0] = '\0'; // truncated — cannot happen for this fixed format/buffer
  return std::string(buf);
}

// shell-quote a path for embedding in a std::system command string.
std::string shq(const std::string &s) {
  std::string out = "'";
  for (char c : s)
    out += (c == '\'') ? std::string("'\\''") : std::string(1, c);
  return out + "'";
}

Expected<neutrino::backend_dispatch_receipt::VerifiedReceipt>
readDispatchReceipt(const std::string &path) {
  auto buffer = MemoryBuffer::getFile(path);
  if (!buffer)
    return createStringError(inconvertibleErrorCode(),
                             "cannot read dispatch receipt");
  return neutrino::backend_dispatch_receipt::verify((*buffer)->getBuffer());
}

json::Object catalogBinding(const neutrino::TargetCatalog &catalog,
                            const neutrino::CatalogTarget &target) {
  json::Object binding{
      {"catalogIdentity", catalog.identity()},
      {"kind", target.externalPackage ? "external-package" : "builtin-core"},
      {"targetIdentity", target.name},
  };
  if (target.externalPackage) {
    const neutrino::backend_package::Descriptor &descriptor =
        catalog.packageFor(target).descriptor();
    binding.insert({"packageManifestDigest", descriptor.manifestDigest});
    binding.insert({"targetProfileDigest", descriptor.profileSummary.digest});
    binding.insert({"targetProfileIdentity", descriptor.targetProfileIdentity});
  }
  return binding;
}

} // namespace

int main(int argc, char **argv) {
  InitLLVM w(argc, argv);
  if (neutrino::handleVersionFlag(argc, argv, "neutrino-bundle"))
    return 0;
  Expected<std::vector<std::string>> packageDirectories =
      neutrino::resolveBackendPackageDirectories(argc, argv);
  if (!packageDirectories) {
    errs() << "error: " << toString(packageDirectories.takeError()) << "\n";
    return EXIT_USAGE;
  }
  Expected<neutrino::TargetCatalog> catalogE =
      neutrino::loadTargetCatalog(*packageDirectories);
  if (!catalogE) {
    errs() << "error: cannot load target catalog: "
           << toString(catalogE.takeError()) << "\n";
    return EXIT_USAGE;
  }
  neutrino::TargetCatalog catalog = std::move(*catalogE);
  cl::ParseCommandLineOptions(argc, argv,
                              "neutrino-bundle: agent bundle runner\n");

  if (showCaps) {
    outs() << capabilitiesDescriptor(catalog);
    return EXIT_OK;
  }

  if (inDir.empty()) {
    errs() << "error: input bundle directory is required (or use "
              "--capabilities)\n";
    return EXIT_USAGE;
  }

  namespace fs = std::filesystem;
  // `source.neu` is the one canonical bundle source name. The name is recorded
  // in bundle.json's source.path (metadata) and only its content sha256 — not
  // the extension — feeds any hash.
  std::string source = (fs::path(inDir.getValue()) / "source.neu").string();
  std::string scenario =
      (fs::path(inDir.getValue()) / "scenario.json").string();
  std::string targetSpec =
      (fs::path(inDir.getValue()) / "target.json").string();

  for (const auto &f : {source, scenario, targetSpec}) {
    if (!fs::exists(f)) {
      errs() << "error: input bundle missing " << f << "\n";
      return EXIT_USAGE;
    }
  }

  // Parse target.json: { "targets": [...] } or { "target": "..." }.
  std::vector<std::string> targets;
  {
    auto buf = MemoryBuffer::getFile(targetSpec);
    if (!buf) {
      errs() << "error: cannot read " << targetSpec << "\n";
      return EXIT_USAGE;
    }
    Expected<json::Value> parsed = json::parse((*buf)->getBuffer());
    if (!parsed) {
      errs() << "error: invalid JSON in " << targetSpec << "\n";
      consumeError(parsed.takeError());
      return EXIT_USAGE;
    }
    json::Object *obj = parsed->getAsObject();
    if (!obj) {
      errs() << "error: " << targetSpec << " must be a JSON object\n";
      return EXIT_USAGE;
    }
    if (json::Array *arr = obj->getArray("targets")) {
      for (json::Value &v : *arr) {
        auto s = v.getAsString();
        if (!s) {
          // A malformed entry is a user input error, not something to skip
          // silently: an agent must see it in the audit trail.
          errs() << "error: " << targetSpec
                 << ": every entry in \"targets\" must be a string\n";
          return EXIT_USAGE;
        }
        targets.push_back(s->str());
      }
    } else if (auto s = obj->getString("target")) {
      targets.push_back(s->str());
    }
    if (targets.empty()) {
      errs() << "error: " << targetSpec << " declares no targets\n";
      return EXIT_USAGE;
    }
  }

  // A target name becomes a path component (<out>/<target>) and a CLI argument,
  // so it must be a safe identifier. Catalog membership is also checked before
  // touching the output tree or spawning any generator.
  for (const std::string &t : targets) {
    bool safe = !t.empty();
    for (char c : t)
      safe &=
          (std::isalnum(static_cast<unsigned char>(c)) || c == '_' || c == '-');
    if (!safe) {
      errs() << "error: " << targetSpec << ": invalid target name '" << t
             << "' (allowed: letters, digits, '_', '-')\n";
      return EXIT_USAGE;
    }
    if (!catalog.find(t)) {
      errs() << "error: " << targetSpec << ": target '" << t
             << "' is absent from verified catalog " << catalog.identity()
             << "\n";
      return EXIT_USAGE;
    }
  }

  const char *genEnv = getenv("NEUTRINO_GEN");
  std::string gen = genEnv ? genEnv : "neutrino-gen";
  std::vector<std::string> resolvedPackageDirectories =
      catalog.packageDirectories();
  std::string packageArguments;
  for (const std::string &directory : resolvedPackageDirectories)
    packageArguments += " --backend-package-dir " + shq(directory);
  const std::string coreIdentity = neutrino::backend_invocation::coreIdentity();
  const std::string catalogIdentity = catalog.identity();
  const std::string childIdentityArguments =
      " --expected-core-identity=" + shq(coreIdentity) +
      " --expected-catalog-identity=" + shq(catalogIdentity);
  std::string outStr = outDir;
  fs::create_directories(outStr);

  // Run generate.<target> per requested target into <out>/<target>/.
  json::Array results;
  bool allOk = true;
  for (const std::string &t : targets) {
    std::string tdir = (fs::path(outStr) / t).string();
    std::string cmd = shq(gen) + " --target=" + shq(t) +
                      " --scenario=" + shq(scenario) + packageArguments +
                      childIdentityArguments + " " + shq(source) + " -o " +
                      shq(tdir);
    int rc = std::system(cmd.c_str()); // NOLINT(cert-env33-c): cmd shell-quotes
                                       // every inserted value (shq)
    // A generator that is killed by a signal (or that std::system could not
    // launch) must count as failure: WEXITSTATUS is only meaningful when the
    // child exited normally, so guard it with WIFEXITED.
    bool exited = (rc != -1) && WIFEXITED(rc);
    int code = exited ? WEXITSTATUS(rc) : -1;
    bool ok = exited && code == 0;
    const neutrino::CatalogTarget &selected = *catalog.find(t);
    std::string bindingError;
    if (ok && selected.externalPackage) {
      std::string receiptPath =
          (fs::path(tdir) / neutrino::backend_dispatch_receipt::kFileName.str())
              .string();
      Expected<neutrino::backend_dispatch_receipt::VerifiedReceipt> receipt =
          readDispatchReceipt(receiptPath);
      if (!receipt) {
        bindingError = toString(receipt.takeError());
      } else {
        const neutrino::backend_package::Descriptor &descriptor =
            catalog.packageFor(selected).descriptor();
        if (receipt->coreIdentity != coreIdentity ||
            receipt->targetIdentity != selected.name ||
            receipt->targetProfileIdentity !=
                descriptor.targetProfileIdentity ||
            receipt->packageManifestDigest != descriptor.manifestDigest)
          bindingError =
              "dispatch receipt does not match the selected catalog entry";
      }
      if (!bindingError.empty()) {
        errs() << "FAIL generate." << t << " catalog binding: " << bindingError
               << "\n";
        ok = false;
        code = EXIT_FAILED;
      }
    }
    allOk &= ok;
    if (!exited && rc != -1 && WIFSIGNALED(rc))
      errs() << "     generate." << t << " killed by signal " << WTERMSIG(rc)
             << "\n";
    errs() << (ok ? "ok   " : "FAIL ") << "generate." << t << " (exit " << code
           << ") -> " << tdir << "\n";

    // A generator killed by a signal (or that std::system could not launch) may
    // never have written its per-target bundle, which would leave the manifest
    // / diagnostics refs below pointing at files that do not exist — an agent
    // would see a structured result but follow a dead link for the failure
    // details. Synthesize a minimal ok:false manifest/diagnostics for whatever
    // is missing so the refs always resolve. On any normal exit neutrino-gen
    // wrote these itself (even on its own failures), so the exists() guards
    // make this a no-op.
    if (!ok) {
      std::string mpath = (fs::path(tdir) / "manifest.json").string();
      std::string dpath = (fs::path(tdir) / "diagnostics.json").string();
      if (!fs::exists(mpath) || !fs::exists(dpath)) {
        fs::create_directories(tdir);
        std::string why = exited ? "generate." + t + " exited " +
                                       std::to_string(code) +
                                       " without writing its bundle"
                          : (rc != -1 && WIFSIGNALED(rc))
                              ? "generate." + t + " was killed by signal " +
                                    std::to_string(WTERMSIG(rc)) +
                                    " before writing its bundle"
                              : "generate." + t + " could not be launched";
        if (!fs::exists(dpath))
          neutrino::writeDiagnostics(dpath, /*ok=*/false,
                                     {{"error", "generator.aborted", why}});
        if (!fs::exists(mpath))
          neutrino::writeManifest(tdir, t, source, scenario, /*artifacts=*/{},
                                  cmd,
                                  /*ok=*/false);
      }
    }
    json::Object result{
        {"capability", "generate." + t},
        {"catalogEntry", catalogBinding(catalog, selected)},
        {"target", t},
        {"ok", ok},
        {"exit", code},
        {"dir", t},
        {"manifest", t + "/manifest.json"},
        {"diagnostics", t + "/diagnostics.json"},
    };
    if (!bindingError.empty())
      result.insert({"catalogBindingError", bindingError});
    results.push_back(std::move(result));
  }

  json::Array packageIdentities;
  for (const neutrino::CatalogTarget &entry : catalog.targets()) {
    if (!entry.externalPackage)
      continue;
    const neutrino::backend_package::Descriptor &descriptor =
        catalog.packageFor(entry).descriptor();
    packageIdentities.push_back(json::Object{
        {"manifestDigest", descriptor.manifestDigest},
        {"targetIdentity", entry.name},
        {"targetProfileDigest", descriptor.profileSummary.digest},
        {"targetProfileIdentity", descriptor.targetProfileIdentity},
    });
  }

  // Top-level output-bundle record.
  json::Object root{
      {"tool", "neutrino-bundle"},
      {"version", kToolVersion},
      {"timestamp", isoNow()},
      {"ok", allOk},
      {"identities",
       json::Object{
           {"catalog", catalogIdentity},
           {"core", coreIdentity},
           {"packages", std::move(packageIdentities)},
       }},
      {"input",
       json::Object{
           {"source", json::Object{{"path", source},
                                   {"sha256", neutrino::sha256OfFile(source)}}},
           {"scenario",
            json::Object{{"path", scenario},
                         {"sha256", neutrino::sha256OfFile(scenario)}}},
           {"target",
            json::Object{{"path", targetSpec},
                         {"sha256", neutrino::sha256OfFile(targetSpec)}}},
       }},
      {"results", std::move(results)},
  };

  std::string bundlePath = (fs::path(outStr) / "bundle.json").string();
  std::error_code ec;
  raw_fd_ostream os(bundlePath, ec);
  if (ec) {
    errs() << "error: could not write " << bundlePath << ": " << ec.message()
           << "\n";
    return EXIT_USAGE;
  }
  os << formatv("{0:2}", json::Value(std::move(root))) << "\n";
  errs() << "wrote " << bundlePath << "\n";

  return allOk ? EXIT_OK : EXIT_FAILED;
}
