-- Generated by the Neutrino Translator from verified MLIR.
-- Idempotent + atomic (a function body runs in a single transaction).
CREATE OR REPLACE FUNCTION accept_oracle_delivery(p_order_id text, p_canonical_claim_hash text, p_observers text[])
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM quorum_acceptance WHERE claim_id = p_order_id AND procedure = 'oracle_delivery') THEN
        RAISE EXCEPTION 'already accepted';
    END IF;
    IF EXISTS (SELECT 1 FROM unnest(p_observers) o(id) WHERE NOT EXISTS (SELECT 1 FROM authorized_observer a WHERE a.observer_set = 'delivery_oracles' AND a.observer_id = o.id)) THEN
        RAISE EXCEPTION 'unauthorized observer';
    END IF;
    IF (SELECT count(*) FROM unnest(p_observers)) <> (SELECT count(DISTINCT o.id) FROM unnest(p_observers) o(id)) THEN
        RAISE EXCEPTION 'duplicate observer';
    END IF;
    IF (SELECT count(DISTINCT o.id) FROM unnest(p_observers) o(id)) < 2 THEN
        RAISE EXCEPTION 'quorum not met';
    END IF;
    INSERT INTO quorum_acceptance(procedure, claim_id, canonical_claim_hash, observer_count)
    VALUES ('oracle_delivery', p_order_id, p_canonical_claim_hash, (SELECT count(DISTINCT o.id) FROM unnest(p_observers) o(id)));
END;
$$;

CREATE OR REPLACE FUNCTION execute_oracle_delivery(p_order_id text, p_buyer_id text, p_seller_id text, p_amount bigint, p_currency text, p_delivery_proof text)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    -- (no computed values)
BEGIN
    IF EXISTS (SELECT 1 FROM coordination_status WHERE idempotency_key = p_order_id AND procedure = 'oracle_delivery' AND reconciled) THEN
        RAISE EXCEPTION 'replay';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM quorum_acceptance WHERE claim_id = p_order_id AND procedure = 'oracle_delivery') THEN
        RAISE EXCEPTION 'quorum not accepted';
    END IF;

    -- idempotency guard (replay-safe): one row per workflow key
    INSERT INTO posting_idempotency(idempotency_key, entry)
    VALUES (p_order_id, 'oracle_delivery')
    ON CONFLICT DO NOTHING;
    IF NOT FOUND THEN
        RETURN;  -- already processed; no double posting
    END IF;


    -- debit buyer_pay (buyer.escrow)
    IF (p_amount) < 0 THEN
        RAISE EXCEPTION 'negative money for buyer_pay';
    END IF;
    INSERT INTO ledger_balance(ledger, party, currency, balance)
    VALUES ('buyer.escrow', p_buyer_id, p_currency, -(p_amount))
    ON CONFLICT (ledger, party, currency)
    DO UPDATE SET balance = ledger_balance.balance + (-(p_amount));
    INSERT INTO postings(procedure, entry, ledger, party, amount, currency, signed_amount, idempotency_key)
    VALUES ('oracle_delivery', 'buyer_pay', 'buyer.escrow', p_buyer_id, p_amount, p_currency, -(p_amount), p_order_id);

    -- credit seller_settle (seller.proceeds)
    IF (p_amount) < 0 THEN
        RAISE EXCEPTION 'negative money for seller_settle';
    END IF;
    INSERT INTO ledger_balance(ledger, party, currency, balance)
    VALUES ('seller.proceeds', p_seller_id, p_currency, p_amount)
    ON CONFLICT (ledger, party, currency)
    DO UPDATE SET balance = ledger_balance.balance + (p_amount);
    INSERT INTO postings(procedure, entry, ledger, party, amount, currency, signed_amount, idempotency_key)
    VALUES ('oracle_delivery', 'seller_settle', 'seller.proceeds', p_seller_id, p_amount, p_currency, p_amount, p_order_id);

    -- balanced invariant: this workflow key must net to zero
    IF (SELECT COALESCE(SUM(signed_amount), 0) FROM postings WHERE procedure = 'oracle_delivery' AND idempotency_key = p_order_id) <> 0 THEN
        RAISE EXCEPTION 'not balanced for %', p_order_id;
    END IF;

    INSERT INTO coordination_status(procedure, idempotency_key, reconciled) VALUES ('oracle_delivery', p_order_id, true)
    ON CONFLICT (procedure, idempotency_key) DO UPDATE SET reconciled = true;
END;
$$;

-- Admission control (): accept_ is the quorum guard. Postgres grants EXECUTE to PUBLIC
-- by default and the observer ids are not secret, so a PUBLIC-callable accept_ is forgeable.
-- REVOKE it (no-access-by-default / fail-safe); the deployer MUST then GRANT it to ONLY the
-- off-chain aggregator role, e.g.:  GRANT EXECUTE ON FUNCTION accept_oracle_delivery(text, text, text[]) TO <aggregator_role>;
REVOKE EXECUTE ON FUNCTION accept_oracle_delivery(text, text, text[]) FROM PUBLIC;
