#!/usr/bin/env bash
# Generated by the Neutrino Translator. Proves the PostgreSQL capability-spec against a
# real PostgreSQL container via docker + psql (no Python). All dynamic SQL is
# fed through quoted heredocs, so the shell never interpolates scenario values;
# SQL string literals are '-escaped.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
CID=$(docker run -d -e POSTGRES_PASSWORD=test -e POSTGRES_USER=test -e POSTGRES_DB=neutrino postgres:16-alpine)
cleanup(){ docker rm -f "$CID" >/dev/null 2>&1 || true; }
trap cleanup EXIT
psql(){ docker exec -i "$CID" psql -v ON_ERROR_STOP=1 -U test -d neutrino "$@"; }
echo 'waiting for postgres...'
ready=0
for _ in $(seq 1 60); do
  if psql -tAq -c 'SELECT 1' >/dev/null 2>&1; then ready=1; break; fi
  sleep 1
done
[ "$ready" = 1 ] || { echo 'FAIL: postgres did not become ready'; exit 1; }

echo NEUTRINO_STAGE=compile
psql -q < "$HERE/schema.sql" >/dev/null
psql -q < "$HERE/procedure.sql" >/dev/null
echo NEUTRINO_STAGE=runtime

psql -q >/dev/null <<'SQL'
INSERT INTO authorized_observer(observer_set, observer_id) VALUES ('delivery_oracles', 'obs-1') ON CONFLICT DO NOTHING;
INSERT INTO authorized_observer(observer_set, observer_id) VALUES ('delivery_oracles', 'obs-2') ON CONFLICT DO NOTHING;
SQL

run(){ psql -tAq >/dev/null <<'SQL'
SELECT accept_oracle_delivery('order-001', 'claim-hash-1', ARRAY['obs-1', 'obs-2']);
SELECT execute_oracle_delivery('order-001', 'buyer-001', 'seller-001', 500, 'USD', 'sha256:11223344556677889900aabbccddeeff00112233445566778899aabbccddeeff');
SQL
}
expect_fail(){ if psql -tAq >/dev/null 2>&1; then echo "FAIL: $1 not refused"; exit 1; fi; }

# 1. quorum gate: execute without an accepted quorum is refused
expect_fail 'unaccepted execute' <<'SQL'
SELECT execute_oracle_delivery('order-001', 'buyer-001', 'seller-001', 500, 'USD', 'sha256:11223344556677889900aabbccddeeff00112233445566778899aabbccddeeff');
SQL
echo '  [1] quorum gate: PASS'

# 2. happy path (attest+execute): balances move; a missing ledger row is upserted
run
V=$(psql -tAq <<'SQL'
SELECT COALESCE(SUM(balance),0) FROM ledger_balance WHERE ledger='buyer.escrow';
SQL
)
[ "$V" = "-500" ] || { echo "FAIL: net mismatch"; exit 1; }
V=$(psql -tAq <<'SQL'
SELECT COALESCE(SUM(balance),0) FROM ledger_balance WHERE ledger='seller.proceeds';
SQL
)
[ "$V" = "500" ] || { echo "FAIL: net mismatch"; exit 1; }
N=$(psql -tAq <<'SQL'
SELECT count(*) FROM postings WHERE idempotency_key='order-001';
SQL
)
[ "$N" = "2" ] || { echo "FAIL: postings=$N"; exit 1; }
echo '  [2] happy path balances + upsert: PASS'

# 3. replay: re-executing a reconciled key is refused
expect_fail 'replay' <<'SQL'
SELECT execute_oracle_delivery('order-001', 'buyer-001', 'seller-001', 500, 'USD', 'sha256:11223344556677889900aabbccddeeff00112233445566778899aabbccddeeff');
SQL
echo '  [3] replay refused: PASS'

# 4. quorum replay: re-accepting an accepted claim is refused
expect_fail 'already accepted' <<'SQL'
SELECT accept_oracle_delivery('order-001', 'claim-hash-1', ARRAY['obs-1', 'obs-2']);
SQL
echo '  [4] quorum replay refused: PASS'

# 5. reconciliation: no drift on the happy path
D=$(psql -tAq <<'SQL'
SELECT count(*) FROM (SELECT idempotency_key FROM postings GROUP BY idempotency_key HAVING SUM(signed_amount)<>0) x;
SQL
)
[ "$D" = "0" ] || { echo "FAIL: unexpected drift rows=$D"; exit 1; }
echo '  [5] reconciliation no drift: PASS'

# 6. reconciliation detects an injected drift
psql -q >/dev/null <<'SQL'
INSERT INTO postings(procedure,entry,ledger,party,amount,currency,signed_amount,idempotency_key)
VALUES ('oracle_delivery','injected','injected','injected',1,'X',1,'order-001');
SQL
D2=$(psql -tAq <<'SQL'
SELECT count(*) FROM (SELECT idempotency_key FROM postings GROUP BY idempotency_key HAVING SUM(signed_amount)<>0) x;
SQL
)
[ "$D2" -ge "1" ] || { echo "FAIL: drift not detected"; exit 1; }
echo '  [6] reconciliation detects injected drift: PASS'

# 7. atomic rollback: a rolled-back accept+execute leaves no rows
psql -q >/dev/null <<'SQL'
BEGIN;
SELECT accept_oracle_delivery('txn-rollback', 'claim-hash-1', ARRAY['obs-1', 'obs-2']);
SELECT execute_oracle_delivery('txn-rollback', 'buyer-001', 'seller-001', 500, 'USD', 'sha256:11223344556677889900aabbccddeeff00112233445566778899aabbccddeeff');
ROLLBACK;
SQL
NR=$(psql -tAq <<'SQL'
SELECT count(*) FROM postings WHERE idempotency_key='txn-rollback';
SQL
)
[ "$NR" = "0" ] || { echo "FAIL: rollback left rows=$NR"; exit 1; }
echo '  [7] atomic rollback: PASS'

echo 'ALL POSTGRES CHECKS PASSED'
