-- Generated by the Neutrino Translator. Coordination tables (not source of truth).
CREATE TABLE IF NOT EXISTS ledger_balance (
    ledger     text   NOT NULL,
    party      text   NOT NULL,
    currency   text   NOT NULL,
    balance    bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (ledger, party, currency)
);

CREATE TABLE IF NOT EXISTS posting_idempotency (
    idempotency_key text NOT NULL,
    entry           text NOT NULL,
    PRIMARY KEY (idempotency_key, entry)
);

CREATE TABLE IF NOT EXISTS postings (
    id             bigserial PRIMARY KEY,
    procedure      text   NOT NULL,
    entry          text   NOT NULL,
    ledger         text   NOT NULL,
    party          text   NOT NULL,
    amount         bigint NOT NULL,
    currency       text   NOT NULL,
    signed_amount  bigint NOT NULL,
    idempotency_key text  NOT NULL
);

-- Coordination lifecycle (): attest -> execute -> reconciled, per workflow key.
-- Upgrade preflight (): refuse a pre-(procedure, key) `coordination_status` rather than
-- silently no-op and fail inside accept_/execute_. Drop the coordination tables and
-- redeploy (they are not source of truth), or migrate each row to its procedure.
DO $$ BEGIN
  IF to_regclass('coordination_status') IS NOT NULL AND NOT EXISTS (
       SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema()
         AND table_name = 'coordination_status' AND column_name = 'procedure') THEN
    RAISE EXCEPTION 'coordination_status predates the (procedure, key) coordination identity (); drop the coordination tables and redeploy, or migrate each row to its procedure';
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS coordination_status (
    procedure       text    NOT NULL,
    idempotency_key text    NOT NULL,
    attested        boolean NOT NULL DEFAULT false,
    reconciled      boolean NOT NULL DEFAULT false,
    PRIMARY KEY (procedure, idempotency_key)
);

-- Oracle S2d (): M-of-N quorum acceptance guard. The observer set (N, members)
-- is seeded at deploy (like the Solidity guard's constructor args); the threshold M is
-- spec-portable and rendered into accept_<proc>. Signature recovery is off-chain (S4).
CREATE TABLE IF NOT EXISTS authorized_observer (
    observer_set text NOT NULL,
    observer_id  text NOT NULL,
    PRIMARY KEY (observer_set, observer_id)
);

-- Upgrade preflight (): refuse a pre-(procedure, key) `quorum_acceptance` rather than
-- silently no-op and fail inside accept_/execute_. Drop the coordination tables and
-- redeploy (they are not source of truth), or migrate each row to its procedure.
DO $$ BEGIN
  IF to_regclass('quorum_acceptance') IS NOT NULL AND NOT EXISTS (
       SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema()
         AND table_name = 'quorum_acceptance' AND column_name = 'procedure') THEN
    RAISE EXCEPTION 'quorum_acceptance predates the (procedure, key) coordination identity (); drop the coordination tables and redeploy, or migrate each row to its procedure';
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS quorum_acceptance (
    procedure            text        NOT NULL,
    claim_id             text        NOT NULL,
    canonical_claim_hash text        NOT NULL,
    observer_count       int         NOT NULL,
    accepted_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (procedure, claim_id)
);
